version: "3"

volumes:
  db-volume:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: girls4girls
    volumes:
      - db-volume:/var/lib/postgres/data

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
